const seedTrails = [
    {
        id: 'creswick-circuit-walk',
        name: 'Creswick Circuit Walk',
        area: 'creswick-regional-park',
        description:
            'An awesome trail exploring some of the bushland to the east of the town of Creswick, Victoria',
        difficulty: 'medium',
        distance: 8.5,
        elevation_gain: 208,
        type: 'loop',
        tags: [
            'Hiking',
            'Walking',
            'Bird watching',
            'Running',
            'Forest',
            'Lake',
            'River',
            'Views',
            'Wildflowers',
            'Wildlife',
        ],
    },
    {
        id: 'mt-buninyong',
        name: 'Mount Buninyong Summit Loop',
        area: 'mt-buninyong',
        description:
            'Mount Buninyong is an extinct volcano situated south of Ballara on the edge of the suburban sprawl.',
        difficulty: 'medium',
        distance: 2.6,
        elevation_gain: 104,
        type: 'loop',
        tags: ['Hiking', 'Mountain biking', 'Walking', 'Forest', 'Views'],
    },
    {
        id: 'cosgrove-reservoir-loop',
        name: 'Cosgrove Reservoir Loop',
        area: 'creswick-vic-australia',
        description:
            'A fun and engaging circuit that covers a good bit of ground around Cosgrove Reservoir in Creswick State Forest.',
        difficulty: 'medium',
        distance: 7.1,
        elevation_gain: 156,
        type: 'loop',
        tags: [
            'Hiking',
            'Mountain biking',
            'Walking',
            'Running',
            'Forest',
            'Lake',
            'Views',
            'Wildlife',
        ],
    },
    {
        id: 'branding-yard-you-yangs',
        name: 'Branding Yard Walk via Northern Range and Rockwell Road',
        area: 'you-yangs-regional-park',
        description: 'This is a fantastic trail through the You Yangs Regional Park.',
        difficulty: 'easy',
        distance: 8.5,
        elevation_gain: 258,
        type: 'loop',
        tags: ['Hiking', 'Walking', 'Running', 'Forest', 'Views', 'No dogs'],
    },
    {
        id: 'goldfields-track-oak-gully-road-and-park-lake',
        name: 'Goldfields Track, Oak Gully Road and Park Lake Loop',
        area: 'creswick-vic-australia',
        description:
            'An enjoyable trail exploring some of the bushland and lakes to the east of Creswick, Victoria, with an optional detour to Cosgrove Reservoir.',
        difficulty: 'Medium',
        distance: 14.2,
        elevation_gain: 333,
        type: 'loop',
        tags: [
            'Hiking',
            'Mountain biking',
            'Walking',
            'Bird watching',
            'Running',
            'Forest',
            'Lake',
            'Partially paved',
            'River',
            'Views',
            'Wildflowers',
            'Wildlife',
        ],
    },
    {
        id: 'lake-wendouree-north-park',
        name: 'North Park via Lake Wendouree',
        area: 'ballarat-vic-australia',
        description:
            'An enjoyable trail exploring some of the bushland and lakes to the east of Creswick, Victoria, with an optional detour to Cosgrove Reservoir.',
        difficulty: 'easy',
        distance: 2.2,
        elevation_gain: 31,
        type: 'loop',
        tags: [
            'Walking',
            'Bird watching',
            'Running',
            'Lake',
            'Partially paved',
            'Views',
            'Wildlife',
        ],
    },
    {
        id: 'yarrowee-river-south',
        name: 'Yarrowee River South Trail',
        area: 'ballarat-vic-australia',
        description: 'A great urban trail located in the city of Ballarat in central Victoria.',
        difficulty: 'Medium',
        distance: 14.3,
        elevation_gain: 221,
        type: 'loop',
        tags: ['Dogs on leash', 'Hiking', 'Road biking', 'Walking', 'Running', 'River'],
    },
];

export default seedTrails;
